## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "MOOP Museum"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-36NWVX0RP8"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "MOOP Museum is a Burning Man theme camp"
  logo = "images/momu_logo.PNG"
  favicon = true

[Params.social]
  github = "https://github.com/dmilad/"
  email = "moopmuseum@gmail.com"
  instagram = "https://instagram.com/moopmuseum"